apiVersion: v2
# You may only uncomment this when using this as a template/bootstrap
# name: chart
description: A Helm chart for Kubernetes
version: 0.2.0

type: application

# Version of the application deploying
# Used as the tag of the image that we are trying to fetch
# You may only uncomment this when using this as a template/bootstrap,
# because this is used as tag for the image
# appVersion: 0.0.1
