{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "..clusterRoleName" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
{{- with .Values.clusterRole.rules }}
rules:
{{ toYaml . }}
{{- end }}
{{- end }}
