apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "..annotations" . | nindent 8 }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      containers:
        - name: {{ include "..name" . }}
          image: "{{ .Values.image.repository }}:{{ include "..version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path | default "healthz" }}
              port: {{ .Values.healthcheck.port | default "http" }}
              {{- with .Values.healthcheck.probes }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path | default "healthz" }}
              port: {{ .Values.healthcheck.port | default "http" }}
              {{- with .Values.healthcheck.probes }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
