{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "..roleName" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
{{- with .Values.role.rules }}
rules:
{{ toYaml . }}
{{- end }}
{{- end }}
