{{- if and .Values.role.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "..labels" . | nindent 4 }}
  name: {{ include "..roleName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "..roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "..serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
