apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  {{- if .Values.service.sessionAffinity }}
  {{ . }}
  {{- end }}
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
